name: emlak_saha_app
description: "Emlak ve saha yönetimi mobil uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_auth: ^6.1.3

  image_picker: ^1.0.7
  geolocator: ^14.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  cupertino_icons: ^1.0.8
intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
